project_name: chezmoi

before:
  hooks:
  - go mod download

builds:
- id: chezmoi-cgo-glibc
  main: ./chezmoi2/main.go
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64
- id: chezmoi-cgo-musl
  main: ./chezmoi2/main.go
  env:
  - CC=/usr/bin/musl-gcc
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64
  ldflags:
  - '-s'
  - '-w'
  - '-X main.version={{.Version}}'
  - '-X main.commit={{.Commit}}'
  - '-X main.date={{.Date}}'
  - '-X main.builtBy=goreleaser'
  - '-linkmode external'
  - '--extldflags "-static"'
- id: chezmoi-nocgo
  main: ./chezmoi2/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - freebsd
  - openbsd
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  - ppc64
  - ppc64le
  goarm:
  - ""
  ignore:
  - goos: darwin
    goarch: 386
  - goos: linux
    goarch: amd64

archives:
- builds:
  - chezmoi-cgo-musl
  - chezmoi-nocgo
  files:
  - LICENSE
  - README.md
  - completions/*
  - docs/*
  replacements:
    386: i386
  format_overrides:
  - goos: windows
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
    - "Merge pull request"

checksum:

nfpms:
- builds:
  - chezmoi-cgo-glibc
  - chezmoi-nocgo
  vendor: "Tom Payne <twpayne@gmail.com>"
  homepage: "https://chezmoi.io/"
  maintainer: "Tom Payne <twpayne@gmail.com>"
  description: "Manage your dotfiles across multiple diverse machines, securely."
  license: MIT
  formats:
  - deb
  - rpm
  dependencies:
  - git
  bindir: /usr/bin
  files:
    "completions/chezmoi-completion.bash": "/usr/share/bash-completion/completions/chezmoi"
    "completions/chezmoi.fish": "/usr/share/fish/completions/chezmoi.fish"
  overrides:
    deb:
      file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      replacements:
        386: i386
        arm: armel
      files:
        "completions/chezmoi.zsh": "/usr/share/zsh/vendor-completions/_chezmoi"
    rpm:
      file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
      replacements:
        amd64: x86_64
        386: i686
        arm: armhfp
        arm64: aarch64
      files:
        "completions/chezmoi.zsh": "/usr/share/zsh/functions/_chezmoi"
- id: apks
  builds:
  - chezmoi-cgo-musl
  - chezmoi-nocgo
  vendor: "Tom Payne <twpayne@gmail.com>"
  homepage: "https://chezmoi.io/"
  maintainer: "Tom Payne <twpayne@gmail.com>"
  description: "Manage your dotfiles across multiple diverse machines, securely."
  license: MIT
  formats:
  - apk
  bindir: /usr/bin

release:

scoop:
  bucket:
    owner: twpayne
    name: scoop-bucket
  commit_author:
    name: Tom Payne
    email: twpayne@gmail.com
  homepage: "https://chezmoi.io"
  description: "Manage your dotfiles across multiple diverse machines, securely."
  license: MIT

snapcrafts:
- builds:
  - chezmoi-cgo-glibc
  - chezmoi-nocgo
  summary: "Manage your dotfiles across multiple diverse machines, securely."
  description: "Manage your dotfiles across multiple diverse machines, securely."
  publish: true
  grade: stable
  confinement: classic
  apps:
    chezmoi:
      completer: completions/chezmoi-completion.bash

source:
  enabled: true
